imports:
    - { resource: '@PrestaCMSThemeBasicBundle/Resources/config/theme/creative.yml' }

parameters:
    presta_cms.page.factory.class: Application\Presta\CMSCoreBundle\Factory\PageFactory

sonata_admin:
  dashboard:
      blocks:
          - { position: right, type: presta_cms.block.dashboard.cms }

presta_cms_core:
    default_website: /website/symfony-prestacms
    default_locale: en
    websites:
        symfony-prestacms:
            path: /website/symfony-prestacms
            hosts:
                dev:
                    en:
                        locale: en
                        host: www.dev-symfony-prestacms.com
                    fr:
                        locale: fr
                        host: www.dev-symfony-prestacms.fr
                prod:
                    en:
                        locale: en
                        host: sandbox.prestacms.com
                    fr:
                        locale: fr
                        host:  sandbox.prestacms.fr
